services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - '/frontend/node_modules'
    environment:
      - HOST_PREFIX=http://localhost:8080
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
